version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: Script/before_install
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: Script/restart_server
      timeout: 300
      runas: ubuntu