version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
<<<<<<< HEAD
   BeforeInstall:
    - location: scripts/installapache.sh
      runas: root
    - location: scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: root
=======
  BeforeInstall:
    - location: Scripts/before_install
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: Scripts/restart_server
      timeout: 300
      runas: ubuntu
>>>>>>> a9da398c239d6630da9c75e17da3b5530e3ec8f0
