version: 0.0
os: linux
github_user: pnarendran23
github_token: XXXXXX
files:
   - source: /
     destination: /var/www/html
     overwrite: true
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: Scripts/installapache.sh
      runas: root
    - location: Scripts/startapache.sh
      runas: root
    - location: Scripts/build.sh
      runas: root
   AfterInstall:
    - location: Scripts/restartapache.sh
      runas: root
    - location: Scripts/deploy.sh
      runas: root
